# .bashrc

# User specific aliases and functions

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias rf='rm -rf'
alias sls='screen -ls'
alias sr='screen -r '
alias sc='screen -S '
alias dsize='du -h --max-depth=1 '
alias gl='git pull origin master'
# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi