# .bashrc

# User specific aliases and functions

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias rf='rf -rf'
alias sls='screen -ls'
alias sr='screen -r '
alias sc='screen -S '
# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi